### PR TITLE
Fix package name and TypeScript casing

### LINKED ISSUE #6: Change repo name and readme to match package name?
The repo name and readme mention `typescript-cleanup-defs`, which is a [404 on npm](https://www.npmjs.com/package/typescript-cleanup-defs)

Screenshot 2024-08-22 at 09 28 05

It appears the official package name is [`typescript-cleanup-definitions`](https://www.npmjs.com/package/typescript-cleanup-definitions)

Maybe the repo name and readme should be updated to reflect that?

### PR DESCRIPTION
**Pull request by karlhorky**
Fixes https://github.com/Viijay-Kr/typescript-cleanup-definitions/issues/6

### CODE REVIEW

**Comment by karlhorky** [comment]
@Viijay-Kr deleted the duplicate Changesets file

**Comment by Viijay-Kr** [comment]
@karlhorky Thanks for the MR. Changesets is not working as expected on main. I guess its some protection rules. Its not able to open MRs in this repo. As soon as I figured that out I will merge your PR

**Review by Viijay-Kr — APPROVED** [review]
@karlhorky Fixed changesets. Always the same damn token issue . I need to remember its always the Personal access token 🤣 . Anyways I m approving this MR

**Comment by karlhorky** [comment]
Oh nice, thanks for the review and merge!

**Pull request merged**
